version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: npm install
      - run: cd todo && react-native run-android
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test